### ISSUE TITLE
Error With Running the samples

### ISSUE THREAD

**Issue by qorbanpour** [NVIDIA/tensorrt-inference-server#103]
I recently pulled Nvidiai Docker container for tensorrt inference engine and Ran Simple_Client.py example
without any change but Inference Engine returns this error which I have not been able to get an insight why it is complaining about . The Error Message is as follow : "nvidia.inferencserver.InferRequestHeader.Input" has no field named "dims" . I checked the message sent by client and it looked fine . I ran both client and engine on same machine and aslo tried to run the engine on another machine but got the same error .
I appreciate if you know what is going on .

with grpc protocol I had another error and it didn't work as well .

 The grpc_image_client.py sample also throws an error: ( if I remeber correctly it was compalining about input size 0 )

python grpc_image_client.py -m resnet50_netdef ~/tensorrt-inference-server/qa/images/mug.jpg

Request 0, batch size 1
Traceback (most recent call last):
  File "grpc_image_client.py", line 325, in <module>
    postprocess(response.meta_data.output, result_filenames[idx], FLAGS.batch_size)
  File "grpc_image_client.py", line 188, in postprocess
    raise Exception("expected 1 result, got {}".format(len(results)))
Exception: expected 1 result, got 0

**Comment by qorbanpour** [comment]
I assume the docker container is not compatible with the master branch ! Docker Container 19.01-py3 . I am going to pull the right branch with github and will give it a try , it should fix the problem

**Comment by qorbanpour** [comment]
building the right branch from github fixed the issue as expected . closing the ticket
