### ISSUE TITLE
exceeds maximum batch size

### ISSUE THREAD

**Issue by mhunsake** [NVIDIA/tensorrt-inference-server#1044]
**Description**

testing image classification model with dynamic batch size to see how it could be used within an ensemble.

_config.pbtxt_
```name: 'my_inception_model'
platform: 'tensorflow_savedmodel'
max_batch_size: 0
input [
   {
      name: 'inception_v3_input'
      data_type: TYPE_FP32
      dims: [ -1, 299, 299, 3]
   }
]
output [
   {
      name: 'dense'
      data_type: TYPE_FP32
      dims: [ -1, 37 ]
      label_filename: 'labels.txt'
   }
]
```
_model status shows it's ready_
```
id: "inference:0"
version: "1.9.0"
uptime_ns: 11065367128
model_status {
  key: "my_inception_model"
  value {
    config {
      name: "my_inception_model"
      platform: "tensorflow_savedmodel"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      input {
        name: "inception_v3_input"
        data_type: TYPE_FP32
        dims: -1
        dims: 299
        dims: 299
        dims: 3
      }
      output {
        name: "dense"
        data_type: TYPE_FP32
        dims: -1
        dims: 37
        label_filename: "labels.txt"
      }
      instance_group {
        name: "my_inception_model"
        count: 1
        gpus: 0
        kind: KIND_GPU
      }
      default_model_filename: "model.savedmodel"
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_READY
        ready_state_reason {
        }
      }
    }
  }
}
ready_state: SERVER_READY
```

_modified image_client.py to read and preprocess 2 test images._
```
    ctx = InferContext(FLAGS.url, protocol, FLAGS.model_name,
                       FLAGS.model_version, FLAGS.verbose, 0, FLAGS.streaming)
    the_result = ctx.run( { input_name : [image_data1, image_data2]}, { output_name : (InferContext.ResultFormat.CLASS, FLAGS.classes) }, 2  )
```
_trying to send two images in a batch fails_
```
Traceback (most recent call last):
  File "./image_client_redux.py", line 300, in <module>
    the_result = ctx.run( { input_name : [image_data1, image_data2]}, { output_name : (InferContext.ResultFormat.CLASS, FLAGS.classes) }, 2  )
  File "/usr/local/lib/python3.6/dist-packages/tensorrtserver/api/__init__.py", line 1514, in run
    self._prepare_request(inputs, outputs, flags, batch_size, corr_id, contiguous_input)
  File "/usr/local/lib/python3.6/dist-packages/tensorrtserver/api/__init__.py", line 1177, in _prepare_request
    _raise_if_error(c_void_p(_crequest_infer_ctx_set_options(self._ctx, options)))
  File "/usr/local/lib/python3.6/dist-packages/tensorrtserver/api/__init__.py", line 258, in _raise_if_error
    raise ex
tensorrtserver.api.InferenceServerException: [ 0] run batch-size 2 exceeds maximum batch size 1 allowed for model 'my_inception_model'
```

**Expected behavior**
I want to have a model defined in the repository that can accept different size batches so that this model can be used in an ensemble.  Based on comments in other issues, I thought that setting max_batch_size: 0 and adding -1 to the input and output dims would allow this. What am I missing?

**Comment by bezero** [comment]
When you set `max_batch_size: 0` you can't send batch request. You are supposed to send a stacked input. In that case, probably you will need to use `RAW` outputs. Something like this:
```
ctx = InferContext(FLAGS.url, protocol, FLAGS.model_name, 
                   FLAGS.model_version, FLAGS.verbose, 0, FLAGS.streaming)
the_result = ctx.run( { input_name : np.stack((image_data1, image_data2))}, 
                   { output_name : InferContext.ResultFormat.RAW })
```
