### ISSUE TITLE
Cannot build TRTIS clients from on Ubuntu 18.04 docker container.

### ISSUE THREAD

**Issue by mhs-achyut** [NVIDIA/tensorrt-inference-server#1178]
**Description**
I am trying to build a docker image for my project starting from the base ubuntu18.04 cuda 10 cudnn 7 devel. I encounter a build error during the build.
**TRTIS Information**
I am using the current master branch
Are you using the TRTIS container or did you build it yourself?
I am trying to build it myself
**To Reproduce**
make -j trtis_clients

**Expected behavior**
I expect the build to proceed without errors

**Error Info**
```
[100%] Linking CXX executable perf_client
/usr/local/lib/python3.6/dist-packages/setuptools/dist.py:453: UserWarning: Normalizing '1.13.0dev' to '1.13.0.dev0'
  normalized_version,
Traceback (most recent call last):
  File "setup.py", line 78, in <module>
    cmdclass={'bdist_wheel': bdist_wheel},
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 134, in setup
    ok = dist.parse_command_line()
  File "/usr/lib/python3.6/distutils/dist.py", line 472, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/dist.py", line 914, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
  File "/usr/lib/python3.6/distutils/dist.py", line 534, in _parse_command_opts
    if not issubclass(cmd_class, Command):
TypeError: issubclass() arg 1 must be a class
make[6]: *** [src/clients/python/api_v1/library/stamp.whl] Error 1
src/clients/python/api_v1/library/CMakeFiles/client-wheel.dir/build.make:63: recipe for target 'src/clients/python/api_v1/library/stamp.whl' failed
make[5]: *** [src/clients/python/api_v1/library/CMakeFiles/client-wheel.dir/all] Error 2
make[5]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1013: recipe for target 'src/clients/python/api_v1/library/CMakeFiles/client-wheel.dir/all' failed
[100%] Built target image_client
[100%] Built target perf_client
Makefile:129: recipe for target 'all' failed
make[4]: *** [all] Error 2
CMakeFiles/trtis-clients.dir/build.make:114: recipe for target 'trtis-clients/src/trtis-clients-stamp/trtis-clients-build' failed
make[3]: *** [trtis-clients/src/trtis-clients-stamp/trtis-clients-build] Error 2
CMakeFiles/Makefile2:492: recipe for target 'CMakeFiles/trtis-clients.dir/all' failed
make[2]: *** [CMakeFiles/trtis-clients.dir/all] Error 2
CMakeFiles/Makefile2:499: recipe for target 'CMakeFiles/trtis-clients.dir/rule' failed
make[1]: *** [CMakeFiles/trtis-clients.dir/rule] Error 2
Makefile:300: recipe for target 'trtis-clients' failed
make: *** [trtis-clients] Error 2
```

**Comment by mhs-achyut** [comment]
@deadeyegoodwin , Can you please take a look?

**Comment by deadeyegoodwin** [comment]
Did you install all the dependencies and follow the other steps described here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/build.html#section-client-libraries-build-using-cmake

**Comment by mhs-achyut** [comment]
We did not need python clients so I commented out the last line in the CMakeLists.txt for now. I am closing this.

**Comment by MenglingD** [comment]
@mhs-achyut , I meet this error also when I build triton-inference-server with cmake. This error arises from the missed python module `wheel`, and this error can be handled by install `wheel`:
```bash
pip3 install wheel
```
Hope this comment makes help.
