### ISSUE TITLE
image_client error

### ISSUE THREAD

**Issue by rotorliu** [NVIDIA/tensorrt-inference-server#3]
When run image_client -m resnet50_netdef -s INCEPTION examples/data/mug.jpg, It's failed!
Server: nvcr.io/nvidia/inferenceserver:18.08.1-py3
Client: Branch:18.08
CUDA Version 9.0.176
Cards: K80

Error message:
failed sending infer request: [inference:0 30] INTERNAL - failed to run model 'resnet50_netdef': [enforce fail at context_gpu.h:171] . Encountered CUDA error: no kernel image is available for execution on the device Error from operator:
input: "gpu_0/res2_0_branch2c_bn" input: "gpu_0/res2_0_branch1_bn" output: "gpu_0/res2_0_branch2c_bn" name: "" type: "Sum" device_option { device_type: 1 cuda_gpu_id: 2 } engine: ""

**Comment by deadeyegoodwin** [comment]
TRTIS supports CUDA Compute Capability 5.2 and later. To see what GPUs this corresponds to use this page: https://developer.nvidia.com/cuda-gpus

K80 is a compute capability 3.7 device and so is not supported. Specifically, your error is saying that TRTIS doesn't have a CUDA kernel available for K80 for one of the operators in the network.

The documentation should have a section describing this requirement. We will add it for the next release.

**Comment by rotorliu** [comment]
> TRTIS supports CUDA Compute Capability 6.0 and later. To see what GPUs this corresponds to use this page: https://developer.nvidia.com/cuda-gpus
> 
> K80 is a compute capability 3.7 device and so is not supported. Specifically, your error is saying that TRTIS doesn't have a CUDA kernel available for K80 for one of the operators in the network.
> 
> The documentation should have a section describing this requirement. We will add it for the next release.

Which version of TRTIS support K80？ Or
How do I build a custom TRTIS to support K80?

**Comment by rotorliu** [comment]
The server start-up OK!

======================
== Inference Server ==
======================

NVIDIA Release 18.08 (build 676502)

Copyright (c) 2018, NVIDIA CORPORATION.  All rights reserved.
Copyright 2018 The TensorFlow Authors.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying
project or file.

I1128 06:58:55.545249 1 server.cc:641] Initializing Inference Server
I1128 06:58:55.545397 1 server.cc:690] Reporting prometheus metrics on port 8002
I1128 06:58:55.546339 1 server.cc:894] Starting server 'inference:0' listening on
I1128 06:58:55.546567 1 server.cc:898]  localhost:8001 for gRPC requests
I1128 06:58:55.548009 1 server.cc:908]  localhost:8000 for HTTP requests
[warn] getaddrinfo: address family for nodename not supported
[evhttp_server.cc : 235] RAW: Entering the event loop ...
I1128 06:58:55.586466 1 server_core.cc:463] Adding/updating models.
I1128 06:58:55.586493 1 server_core.cc:518]  (Re-)adding model: resnet50_netdef
I1128 06:58:55.686701 1 basic_manager.cc:716] Successfully reserved resources to load servable {name: resnet50_netdef version: 1}
I1128 06:58:55.686745 1 loader_harness.cc:66] Approving load for servable version {name: resnet50_netdef version: 1}
I1128 06:58:55.686761 1 loader_harness.cc:74] Loading servable version {name: resnet50_netdef version: 1}
I1128 06:58:56.291246 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_0_gpu0 on GPU 0 (3.7) using init_model.netdef and model.netdef
I1128 06:58:58.383994 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_0_gpu1 on GPU 1 (3.7) using init_model.netdef and model.netdef
I1128 06:58:59.493740 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_0_gpu2 on GPU 2 (3.7) using init_model.netdef and model.netdef
I1128 06:59:00.750374 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_0_gpu3 on GPU 3 (3.7) using init_model.netdef and model.netdef
I1128 06:59:02.265934 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_1_gpu0 on GPU 0 (3.7) using init_model.netdef and model.netdef
I1128 06:59:02.936991 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_1_gpu1 on GPU 1 (3.7) using init_model.netdef and model.netdef
I1128 06:59:04.250893 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_1_gpu2 on GPU 2 (3.7) using init_model.netdef and model.netdef
I1128 06:59:05.003950 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_1_gpu3 on GPU 3 (3.7) using init_model.netdef and model.netdef
I1128 06:59:06.234982 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_2_gpu0 on GPU 0 (3.7) using init_model.netdef and model.netdef
I1128 06:59:07.233598 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_2_gpu1 on GPU 1 (3.7) using init_model.netdef and model.netdef
I1128 06:59:08.875509 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_2_gpu2 on GPU 2 (3.7) using init_model.netdef and model.netdef
I1128 06:59:09.646043 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_2_gpu3 on GPU 3 (3.7) using init_model.netdef and model.netdef
I1128 06:59:10.984277 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_3_gpu0 on GPU 0 (3.7) using init_model.netdef and model.netdef
I1128 06:59:11.741762 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_3_gpu1 on GPU 1 (3.7) using init_model.netdef and model.netdef
I1128 06:59:13.107415 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_3_gpu2 on GPU 2 (3.7) using init_model.netdef and model.netdef
I1128 06:59:13.907042 1 netdef_bundle.cc:170] Creating instance resnet50_netdef_0_3_gpu3 on GPU 3 (3.7) using init_model.netdef and model.netdef
I1128 06:59:15.349943 1 loader_harness.cc:86] Successfully loaded servable version {name: resnet50_netdef version: 1}

**Comment by rotorliu** [comment]
Thank you very much！

**Comment by pranavpsv** [comment]
I was attempting to make Triton Inference Server work with Tesla K80 for pytorch models, and I modified TORCH_CUDA_ARCH_LIST to include 3.7 inside the container. However, it was still serving my pytorch model on the CPU.

**Comment by deadeyegoodwin** [comment]
Did you try using a recent Triton and use the --min-supported-compute-capability flag?

**Comment by pranavpsv** [comment]
I was using Triton 20.03.1 version, but I did not know about the  --min-supported-compute-capability flag, Thank you, I will try it and update.

**Comment by pranavpsv** [comment]
Just tried it out, it is loading the model on the GPU, thank you! Why isn't the default min-supported-compute-capability low enough to support GPUs like Tesla K80?

**Comment by pranavpsv** [comment]
@deadeyegoodwin Using the min-compute-capability flag, I'm able to load my BERT pytorch model on the Tesla K80 GPU, however making an inference request is failing (using `perf_client -m bert_pt --input-data zero`). Making this same inference request on V100 GPU is working successfully (with same model repository). I turned on verbose logging on the server container and got this error when running perf_client on Tesla K80 for the pytorch bert model.

The error on client container:
```
Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.
[ 0] INTERNAL - Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: [inference:0 13] INTERNAL - failed to run model 'bert_pt_0_gpu0


```

The error on server container (with verbose logging):

```
Traceback (most recent call last):
Serialized   File "code/__torch__.py", line 9
    _0 = self.model
    input_ids = torch.to(data, dtype=4, layout=0, device=torch.device("cuda"), pin_memory=False, non_blocking=False, copy=False, memory_format=None)
    return ((_0).forward(input_ids, ),)
             ~~~~~~~~~~~ <--- HERE
Serialized   File "code/__torch__/transformers/modeling_bert.py", line 10, in forward
    input_ids: Tensor) -> Tensor:
    _0 = self.classifier
    _1 = (self.dropout).forward((self.bert).forward(input_ids, ), )
                                 ~~~~~~~~~~~~~~~~~~ <--- HERE
    return (_0).forward(_1, )
class BertModel(Module):
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/transformers/modeling_bert.py(726): forward
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/transformers/modeling_bert.py(1267): forward
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
pt_transform.py(9): forward
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/jit/__init__.py(1027): trace_module
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/jit/__init__.py(875): trace
pt_transform.py(13): <module>
Serialized   File "code/__torch__/transformers/modeling_bert.py", line 28, in forward
    _8 = ops.prim.NumToTensor(torch.size(input_ids, 1))
    _9 = int(_8)
    attention_mask = torch.ones([_7, int(_8)], dtype=6, layout=0, device=torch.device("cuda:0"), pin_memory=False)
                     ~~~~~~~~~~ <--- HERE
    input = torch.zeros([_6, _9], dtype=4, layout=0, device=torch.device("cuda:0"), pin_memory=False)
    _10 = torch.slice(attention_mask, 0, 0, 9223372036854775807, 1)

I0706 10:53:02.043244 1 pinned_memory_manager.cc:157] pinned memory deallocation: addr 0x2030c0090
I0706 10:53:02.043266 1 trtserver.cc:1781] Infer failed: failed to run model 'bert_pt_0_gpu0
```
The google drive link to the model_repository (with config.pbtxt): [Link](https://drive.google.com/drive/folders/1O7PdlNQN1SMATmw2O652VtnHFTjW5NYw?usp=sharing)
I used version 20.03.1 for both server and client containers.
What would be the fix to make inference requests possible on Tesla K80 GPU with such models?

**Comment by pranavpsv** [comment]
@deadeyegoodwin I also just ran triton server version 20.06 with the bert_model with the model_repository in the comment above and used perf_client on the model. It faces the same problem with a slightly different error message.
Client container error:
```
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: failed to run model 'bert_pt_0_gpu0
```

Server container error (when running perf_client for the first time):
```
I0706 11:18:57.880525 1 pinned_memory_manager.cc:130] pinned memory allocation: size 1024, addr 0x2030c0090
THCudaCheck FAIL file=/tmp/pip-req-build-o3be_uv8/aten/src/THC/generic/THCTensorMathReduce.cu line=73 error=209 : no kernel image is available for execution on the device
I0706 11:18:57.949145 1 libtorch_backend.cc:772] cuda runtime error (209) : no kernel image is available for execution on the device at /tmp/pip-req-build-o3be_uv8/aten/src/THC/generic/THCTensorMathReduce.cu:73
I0706 11:18:57.949207 1 pinned_memory_manager.cc:157] pinned memory deallocation: addr 0x2030c0090
```

Server container error (when running perf_client for the second time):

```
I0706 11:19:58.466625 1 libtorch_backend.cc:772] The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__.py", line 9, in forward
    _0 = self.model
    input_ids = torch.to(data, dtype=4, layout=0, device=torch.device("cuda"), pin_memory=False, non_blocking=False, copy=False, memory_format=None)
    return ((_0).forward(input_ids, ),)
             ~~~~~~~~~~~ <--- HERE
  File "code/__torch__/transformers/modeling_bert.py", line 10, in forward
    input_ids: Tensor) -> Tensor:
    _0 = self.classifier
    _1 = (self.dropout).forward((self.bert).forward(input_ids, ), )
                                 ~~~~~~~~~~~~~~~~~~ <--- HERE
    return (_0).forward(_1, )
class BertModel(Module):
  File "code/__torch__/transformers/modeling_bert.py", line 28, in forward
    _8 = ops.prim.NumToTensor(torch.size(input_ids, 1))
    _9 = int(_8)
    attention_mask = torch.ones([_7, int(_8)], dtype=6, layout=0, device=torch.device("cuda:0"), pin_memory=False)
                     ~~~~~~~~~~ <--- HERE
    input = torch.zeros([_6, _9], dtype=4, layout=0, device=torch.device("cuda:0"), pin_memory=False)
    _10 = torch.slice(attention_mask, 0, 0, 9223372036854775807, 1)

Traceback of TorchScript, original code (most recent call last):
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/transformers/modeling_bert.py(726): forward
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/transformers/modeling_bert.py(1267): forward
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
pt_transform.py(9): forward
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/jit/__init__.py(1027): trace_module
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/jit/__init__.py(875): trace
pt_transform.py(13): <module>
RuntimeError: CUDA error: no kernel image is available for execution on the device

I0706 11:19:58.466697 1 pinned_memory_manager.cc:157] pinned memory deallocation: addr 0x2030c0090
```

**Comment by deadeyegoodwin** [comment]
The reason Triton only supports CUDA Compute capability 6.0 and higher is because that is all that we test and that is all that the underlying DL frameworks that we depend on test. So you can set the flag so that Triton uses an older GPU, but that is no guarantee that your model will work correctly on that GPU.

**Comment by pranavpsv** [comment]
Got it, thank you for the info. Are there any plans to support Tesla K80 from Triton in the future given its popularity for serving models?

**Comment by deadeyegoodwin** [comment]
There are no plans to support K80. The limitation comes from the underlying framework backends and they are typically forward looking. If pytorch has support for K80 you could try building it yourself with that support enabled as described in the documentation.

**Comment by VJAYSLN** [comment]
> @deadeyegoodwin I also just ran triton server version 20.06 with the bert_model with the model_repository in the comment above and used perf_client on the model. It faces the same problem with a slightly different error message.
> Client container error:
> 
> ```
> *** Measurement Settings ***
>   Batch size: 1
>   Measurement window: 5000 msec
>   Using synchronous calls for inference
>   Stabilizing using average latency
> 
> Request concurrency: 1
> Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
> Thread [0] had error: failed to run model 'bert_pt_0_gpu0
> ```
> 
> Server container error (when running perf_client for the first time):
> 
> ```
> I0706 11:18:57.880525 1 pinned_memory_manager.cc:130] pinned memory allocation: size 1024, addr 0x2030c0090
> THCudaCheck FAIL file=/tmp/pip-req-build-o3be_uv8/aten/src/THC/generic/THCTensorMathReduce.cu line=73 error=209 : no kernel image is available for execution on the device
> I0706 11:18:57.949145 1 libtorch_backend.cc:772] cuda runtime error (209) : no kernel image is available for execution on the device at /tmp/pip-req-build-o3be_uv8/aten/src/THC/generic/THCTensorMathReduce.cu:73
> I0706 11:18:57.949207 1 pinned_memory_manager.cc:157] pinned memory deallocation: addr 0x2030c0090
> ```
> 
> Server container error (when running perf_client for the second time):
> 
> ```
> I0706 11:19:58.466625 1 libtorch_backend.cc:772] The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript, serialized code (most recent call last):
>   File "code/__torch__.py", line 9, in forward
>     _0 = self.model
>     input_ids = torch.to(data, dtype=4, layout=0, device=torch.device("cuda"), pin_memory=False, non_blocking=False, copy=False, memory_format=None)
>     return ((_0).forward(input_ids, ),)
>              ~~~~~~~~~~~ <--- HERE
>   File "code/__torch__/transformers/modeling_bert.py", line 10, in forward
>     input_ids: Tensor) -> Tensor:
>     _0 = self.classifier
>     _1 = (self.dropout).forward((self.bert).forward(input_ids, ), )
>                                  ~~~~~~~~~~~~~~~~~~ <--- HERE
>     return (_0).forward(_1, )
> class BertModel(Module):
>   File "code/__torch__/transformers/modeling_bert.py", line 28, in forward
>     _8 = ops.prim.NumToTensor(torch.size(input_ids, 1))
>     _9 = int(_8)
>     attention_mask = torch.ones([_7, int(_8)], dtype=6, layout=0, device=torch.device("cuda:0"), pin_memory=False)
>                      ~~~~~~~~~~ <--- HERE
>     input = torch.zeros([_6, _9], dtype=4, layout=0, device=torch.device("cuda:0"), pin_memory=False)
>     _10 = torch.slice(attention_mask, 0, 0, 9223372036854775807, 1)
> 
> Traceback of TorchScript, original code (most recent call last):
> /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/transformers/modeling_bert.py(726): forward
> /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
> /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
> /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/transformers/modeling_bert.py(1267): forward
> /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
> /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
> pt_transform.py(9): forward
> /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
> /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
> /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/jit/__init__.py(1027): trace_module
> /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/jit/__init__.py(875): trace
> pt_transform.py(13): <module>
> RuntimeError: CUDA error: no kernel image is available for execution on the device
> 
> I0706 11:19:58.466697 1 pinned_memory_manager.cc:157] pinned memory deallocation: addr 0x2030c0090
> ```

I too got this same above  mentioned error. Here only difference is i was load the triton server and inferring request on my CPU machine, since i have only CPU machines. 1) Is there any mandatory to load the bert model on GPU? 2) can we load any kind of  torch-scripted models with image_client/perf_client? Any Alternative way instead of using image_client/perf_client? 3) While inferring requests, if we don't send any inputs with the requests, then how the requests can works?

**Comment by deadeyegoodwin** [comment]
1. I don't know. If the model has operations that only have a GPU implementation then it does need to run on GPU.
2. The clients don't load the model... perf_client works with any model but you may need to provide actual input tensors because some models don't work correctly if you use the perf_client default of sending zero or random tensor data.
3. If you don't send inputs you will get back an error from the server.

Try running the model using the pytorch APIs directly to see if the model works outside of Triton.
