### ISSUE TITLE
InferenceServerException: [ 0] invalid size 22110 bytes for input 'gpu_0/data', expects 4 bytes

### ISSUE THREAD

**Issue by gr8Adakron** [NVIDIA/tensorrt-inference-server#438]
I have pulled the tensorrt-inference-server container:
> https://ngc.nvidia.com/catalog/containers/nvidia:tensorrtserver

And client-api from:(latest-version)
> https://github.com/NVIDIA/tensorrt-inference-server/releases

**Other configurations:**
CUDA: 9.0
NCCL: 2.2
UBUNTU: 16.04
TENSORFLOW-GPU: 1.12
PYTHON: 3.6
MACHINE TYPE: 4 K80 GPU(Google compute server)

Command used to start **Tensorrt-inference-server**:

> **sudo nvidia-docker run --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/home/serving/tensorrt-example/model_repository:/models nvcr.io/nvidia/tensorrtserver:19.06-py3 trtserver --model-store=/models**

**Models been used are the sample-model given in repo**:
https://github.com/NVIDIA/tensorrt-inference-server/tree/master/docs/examples/model_repository

Client Script:

```
import argparse
import numpy as np
import os
from builtins import range
from PIL import Image
from tensorrtserver.api import *
import tensorrtserver.api.model_config_pb2 as model_config

FLAGS = None

def parse_model(url, protocol, model_name, verbose=False):
    """
    Check the configuration of a model to make sure it meets the
    requirements for an image classification network (as expected by
    this client)
    """
    ctx = ServerStatusContext(url, protocol, model_name, verbose)
    server_status = ctx.get_server_status()

    if model_name not in server_status.model_status:
        raise Exception("unable to get status for '" + model_name + "'")

    status = server_status.model_status[model_name]
    config = status.config

    if len(config.input) != 1:
        raise Exception("expecting 1 input, got {}".format(len(config.input)))
    if len(config.output) != 1:
        raise Exception("expecting 1 output, got {}".format(len(config.output)))

    input = config.input[0]
    output = config.output[0]

    return (input.name, output.name, config.max_batch_size)

def postprocess(results, filenames, batch_size):
    """
    Post-process results to show classifications.
    """
    if len(results) != 1:
        raise Exception("expected 1 result, got {}".format(len(results)))

    batched_result = list(results.values())[0]
    if len(batched_result) != batch_size:
        raise Exception("expected {} results, got {}".format(batch_size, len(batched_result)))
    if len(filenames) != batch_size:
        raise Exception("expected {} filenames, got {}".format(batch_size, len(filenames)))

    for (index, result) in enumerate(batched_result):
        print("Image '{}':".format(filenames[index]))
        for cls in result:
            print("    {} ({}) = {}".format(cls[0], cls[2], cls[1]))


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-v', '--verbose', action="store_true", required=False, default=False,
                        help='Enable verbose output')
    parser.add_argument('-c', '--classes', type=int, required=False, default=1,
                        help='Number of class results to report. Default is 1.')
    parser.add_argument('-u', '--url', type=str, required=False, default='localhost:8000',
                        help='Inference server URL. Default is localhost:8001.')
    parser.add_argument('-i', '--protocol', type=str, required=False, default='HTTP',
                        help='Protocol (HTTP/gRPC) used to ' +
                        'communicate with inference service. Default is HTTP.')
    parser.add_argument('image_filename', type=str, nargs='?', default="test_2.jpg",
                        help='Input image / Input folder.')
    FLAGS = parser.parse_args()

    protocol = ProtocolType.from_str(FLAGS.protocol)

    input_name, output_name, batch_size = parse_model(
        FLAGS.url, protocol, "resnet50_netdef", FLAGS.verbose)

    ctx = InferContext(FLAGS.url, protocol, "resnet50_netdef",
                       -1, FLAGS.verbose)

    filenames = []
    if os.path.isdir(FLAGS.image_filename):
        filenames = [os.path.join(FLAGS.image_filename, f)
                     for f in os.listdir(FLAGS.image_filename)
                     if os.path.isfile(os.path.join(FLAGS.image_filename, f))]
    else:
        filenames = [FLAGS.image_filename,]

    filenames.sort()

    # Set batch size to the smaller value of image size and max batch size
    if len(filenames) <= batch_size:
        batch_size = len(filenames)
    else:
        print("The number of images exceeds maximum batch size," \
                "only the first {} images, sorted by name alphabetically," \
                " will be processed".format(batch_size))

    # Preprocess the images into input data according to model
    # requirements
    image_data = []
    print(filenames)
    for idx in range(batch_size):
        with open(filenames[idx], "rb") as fd:
            image_data.append(np.array([fd.read()], dtype=bytes))

    # Send requests of batch_size images.
    input_filenames = []
    input_batch = []
    for idx in range(batch_size):
        input_filenames.append(filenames[idx])
        input_batch.append(image_data[idx])

    # Send request
    #print(input_batch)
    result = ctx.run(
        { input_name : input_batch },
        { output_name : (InferContext.ResultFormat.CLASS, FLAGS.classes) },
        batch_size)

    postprocess(result, input_filenames, batch_size)

```
Image I am trying to test:
![Webp net-resizeimage](https://user-images.githubusercontent.com/16715364/60822490-27cdbc80-a1c3-11e9-99b8-96b8689d6654.jpg)

**ERROR ENCOUNTER:**
```
Traceback (most recent call last):
  File "trt_sclient.py", line 117, in <module>
    batch_size)
  File "/home/serving/.virtualenvs/trt5.1.5/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 873, in run
    self._prepare_request(inputs, outputs, flags, batch_size, contiguous_input)
  File "/home/serving/.virtualenvs/trt5.1.5/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 687, in _prepare_request
    c_uint64(input_value.size * input_value.itemsize))))
  File "/home/serving/.virtualenvs/trt5.1.5/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 180, in _raise_if_error
    raise ex
tensorrtserver.api.InferenceServerException: [ 0] invalid size 22110 bytes for input 'gpu_0/data', expects 4 bytes
```

**Comment by gr8Adakron** [comment]
@swarren @aaronp24 @mkolod @lukeyeager Any help is appreciated.

**Comment by GuanLuo** [comment]
The first thing you want to look at is if the numpy array created from the image matches the input shape and data type required by the model, for instance, resnet accepts input with shape [224, 224, 3] and data type FP32. In your case, you will need to preprocess your image as `fd.read()` returns the binary of the file which is encoded in jpg format.

**Comment by gr8Adakron** [comment]
thanks.
