### ISSUE TITLE
TRT+CELERY unexpected: InferenceServerException('c_void_p(122485 792)',)

### ISSUE THREAD

**Issue by gr8Adakron** [NVIDIA/tensorrt-inference-server#477]
I have been trying to integrate Celery with TRT-Inference, where celery-task will call the TensorRT-Inference-server object to get the model prediction. Strangely, its throwing error inorder to pickle the TensorRT-class' object.

This is my inference class code:
```

class TensorRT_Client():
    """docstring for TensorRT_Client"""
    def __init__(self):
        super(TensorRT_Client, self).__init__()
        self.url      = "localhost:8001"
        self.protocol = "HTTP"
        self.verbose  = False
        self.classes  = 1

    def preprocessing(self, image_path):
        with tf.device('/cpu:0'):
            image     = keras_image.load_img(image_path,target_size=(224,224))
            image     = keras_image.img_to_array(image) 
            image     = xpreprocess_input(image)
        return image
    
    def decode_image(self,jpeg_file,width,height):
        with tf.device('/cpu:0'):
            decoder_graph = tf.Graph()
            with decoder_graph.as_default():
                decoded_image = tf.image.decode_png(jpeg_file, channels=3)
                decoded_image = tf.image.central_crop(decoded_image, 1)
                decoded_image = tf.image.resize_images(decoded_image, (width,height))
                normalized_image = tf.divide(decoded_image, 255)
                # reshaped_image = tf.reshape(normalized_image, [-1, 331, 331, 3])
            with tf.Session(graph = decoder_graph) as image_session:
            # image_session = tf.Session(graph = decoder_graph)
                input_0 = image_session.run(normalized_image)
        return input_0

    def preprocessing_tensorflow(self,image_path,width,height):
        with tf.gfile.FastGFile(image_path, 'rb') as jpeg_file_raw:
            jpeg_file = jpeg_file_raw.read()
            input_0 = self.decode_image(jpeg_file,width,height)
        return input_0

    def preprocessing_keras(self,image_path,width,height,algo='xception'):
        with tf.device('/cpu:0'):
            image   = keras_image.load_img(image_path,target_size=(width,height))
            image   = keras_image.img_to_array(image) 
            print(f"============ {algo} ============")
            if(algo=='resnet50'):
                print("=========== RESNET50 PREPROCESSING ===============")
                image   = resnet_50_preprocess_input(image)
            elif(algo=='densenet'):
                print("=========== DENSENET PREPROCESSING ===============")
                image = densenet_preprocess_input(image)
            elif(algo=='mobilenet'):
                print("=========== MOBILENET PREPROCESSING ===============")
                image = mobilenet_preprocess_input(image)
            elif(algo=='xception'):
                image = densenet_preprocess_input(image)
            else:
                image   = xpreprocess_input(image)
        return image

    def preprocessing_mxnet(self,filename,width,height):
        img = cv2.imread(filename)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = cv2.resize(img, (width,height,))
        img = np.swapaxes(img, 0, 2)
        img = np.swapaxes(img, 1, 2)
        img = img.astype('float')
        img[0,:,:] -= 123.68
        img[1,:,:] -= 116.779
        img[2,:,:] -= 103.939
        #img = img[np.newaxis, :]
        swap_img_1 = np.swapaxes(img, 0, 1)
        #print(swap_img_1.shape)
        swap_img_2 = np.swapaxes(swap_img_1, 1, 2)
        #print(swap_img_2.shape)
        swap_img_3 = np.swapaxes(swap_img_2, 0, 1)
        return swap_img_2

    def parse_model(self, url, protocol, model_name, verbose=False):
        """
        Check the configuration of a model to make sure it meets the
        requirements for an image classification network (as expected by
        this client)
        """
        ctx = ServerStatusContext(url, protocol, model_name, verbose)
        server_status = ctx.get_server_status()

        if model_name not in server_status.model_status:
            raise Exception("unable to get status for '" + model_name + "'")

        status = server_status.model_status[model_name]
        config = status.config

        if len(config.input) != 1:
            raise Exception("expecting 1 input, got {}".format(len(config.input)))
        if len(config.output) != 1:
            raise Exception("expecting 1 output, got {}".format(len(config.output)))

        input  = config.input[0]
        output = config.output[0]

        return (input.name, output.name, config.max_batch_size)
    
    def extract_model_data(self,individual_meta_catalogue):
        input_tensor  = individual_meta_catalogue["input_tensor"]
        output_tensor = individual_meta_catalogue["output_tensor"]
        signature     = individual_meta_catalogue["signature"]
        model_name    = individual_meta_catalogue["model_name"]
        labels_list   = []
        model_type    = individual_meta_catalogue["model_type"]
        if('width' in list(individual_meta_catalogue.keys())):
            width     = individual_meta_catalogue["width"]
            height    = individual_meta_catalogue["height"]
        else:
            print(" > Now getting default size: 224 X 224.")
            width     = 224
            height    = 224
            

        if('algo' in list(individual_meta_catalogue.keys())):
            algo      = individual_meta_catalogue["algo"]
        else:
            algo      = 'xception'
            
        if(signature == "default"): 
            signature = tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY
        return input_tensor,output_tensor,signature,model_name,labels_list,model_type,width,height,algo

    
    def postprocess(self, results, filenames, batch_size):
        """
        Post-process results to show classifications.
        """
        id2prediction_mapping = {}
        if len(results) != 1:
            raise Exception("expected 1 result, got {}".format(len(results)))

        batched_result = list(results.values())[0]
        if len(batched_result) != batch_size:
            raise Exception("expected {} results, got {}".format(batch_size, len(batched_result)))
        if len(filenames) != batch_size:
            raise Exception("expected {} filenames, got {}".format(batch_size, len(filenames)))

        for (index, result) in enumerate(batched_result):
            print("Image '{}':".format(filenames[index]))
            _id         = format(filenames[index])
            prediction  = result[0][2] #..> prediction
            probability = result[0][1] #..> probability float(format(a,'.3f'))
            id2prediction_mapping[_id] = {
                "prediction": prediction,
                "probability": float(format(probability,'.3f'))
            }
        return id2prediction_mapping

    def preprocess_supervisor(self,images_path,model_type,model_name,width,height,algo):
        height, width = int(height), int(width)
        preprocessed_input = []
        for single_image_path in images_path:
            if(model_type=="tensorflow"):
                preprocessed_input.append(self.preprocessing_tensorflow(single_image_path,width,height))
            elif(model_type=="mxnet"):
                preprocessed_input.append(self.preprocessing_mxnet(single_image_path,width,height))
            elif(model_type=="keras"):
                preprocessed_input.append(self.preprocessing_keras(single_image_path,width,height,algo))
        return preprocessed_input
    
    def executor(self,model_meta,model_name,batch_images_id2name_mapping,RAW=False):
        _ids, images_path  = list(batch_images_id2name_mapping.keys()), list(batch_images_id2name_mapping.values())
        input_tensor,output_tensor,signature,model_name,labels_list,model_type,width,height,algo = self.extract_model_data(model_meta)
        protocol           = ProtocolType.from_str(self.protocol)
        actual_batch_size  = len(images_path)
        input_batch        = []
        input_batch        = self.preprocess_supervisor(images_path,model_type,model_name,width,height,algo)
        
        input_name, output_name, expected_batch_size = self.parse_model(
                        url         = self.url, 
                        protocol    = protocol, 
                        model_name  =  f"{model_name}", 
                        verbose     = self.verbose)

        ctx            = InferContext(self.url, 
                        protocol, 
                        f"{model_name}", 
                        -1, 
                        self.verbose)
        if(RAW):
            id2resultsraw_mapping = {}
            results               = ctx.run(
                    { input_name : input_batch },
                    { output_name : (InferContext.ResultFormat.RAW) },
                    actual_batch_size)
            results_raw           = list(results.values())[0]
            print(results_raw)
            for index,_id in enumerate(_ids):
                id2resultsraw_mapping[_id] = results_raw[index]
            return id2resultsraw_mapping
        else:
            results                = ctx.run(
                    { input_name : input_batch },
                    { output_name : (InferContext.ResultFormat.CLASS, self.classes) },
                    actual_batch_size)
            
            id2prediction_mapping = self.postprocess(results, _ids, actual_batch_size)
            return id2prediction_mapping
    
    def colonel(self,batch_imgs_path,model_meta,model_name):
        batch_images_id2name_mapping = {single_pack["id"]:single_pack["image_path"] for single_pack in batch_imgs_path}
        output = self.executor(model_meta,model_name,batch_images_id2name_mapping,RAW=False)
        return output

```

This is the error, which I get even before the task start to perform the inference.

Error:
```

tensorrtserver.api.InferenceServerException: c_void_p(122481088)
[2019-07-18 17:12:25,042: ERROR/ForkPoolWorker-66] Task pt_conductor.tasks.batch_mode_imagepath[c
902c2ec-9042-4e8a-9c35-c191df62126b] raised unexpected: InferenceServerException('c_void_p(122485
792)',)
Traceback (most recent call last):
  File "/home/serving/.virtualenvs/api-celery/lib/python3.6/site-packages/celery/app/trace.py", l
ine 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/serving/.virtualenvs/api-celery/lib/python3.6/site-packages/celery/app/trace.py", l
ine 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/serving/master-api/pt_conductor/tasks.py", line 40, in batch_mode_imagepath
    output          = trt_obj_pt.colonel(batch_imgs_path,model_meta,model_name)
  File "/home/serving/master-api/pt_conductor/trt_clients.py", line 368, in colonel
    output = self.executor(model_meta,model_name,batch_images_id2name_mapping,RAW=False)
  File "/home/serving/master-api/pt_conductor/trt_clients.py", line 361, in executor
    actual_batch_size)
  File "/home/serving/.virtualenvs/api-celery/lib/python3.6/site-packages/tensorrtserver/api/__in
it__.py", line 873, in run
    self._prepare_request(inputs, outputs, flags, batch_size, contiguous_input)
  File "/home/serving/.virtualenvs/api-celery/lib/python3.6/site-packages/tensorrtserver/api/__in
it__.py", line 687, in _prepare_request
    c_uint64(input_value.size * input_value.itemsize))))
  File "/home/serving/.virtualenvs/api-celery/lib/python3.6/site-packages/tensorrtserver/api/__in
it__.py", line 180, in _raise_if_error
    raise ex
tensorrtserver.api.InferenceServerException: c_void_p(122485792)
[2019-07-18 17:12:25,047: ERROR/MainProcess] Task handler raised error: <MaybeEncodingError: Erro
r sending result: '"(1, <ExceptionInfo: InferenceServerException('c_void_p(122485792)',)>, None)"
'. Reason: ''PicklingError("Can\'t pickle <class \'tensorrtserver.api.InferenceServerException\'>
: it\'s not the same object as tensorrtserver.api.InferenceServerException",)''.>
Traceback (most recent call last):
  File "/home/serving/.virtualenvs/api-celery/lib/python3.6/site-packages/billiard/pool.py", line
 362, in workloop
    put((READY, (job, i, result, inqW_fd)))
  File "/home/serving/.virtualenvs/api-celery/lib/python3.6/site-packages/billiard/queues.py", li
ne 366, in put
    self.send_payload(ForkingPickler.dumps(obj))
  File "/home/serving/.virtualenvs/api-celery/lib/python3.6/site-packages/billiard/reduction.py",
 line 56, in dumps
    cls(buf, protocol).dump(obj)
billiard.pool.MaybeEncodingError: Error sending result: '"(1, <ExceptionInfo: InferenceServerException('c_void_p(122485792)',)>, None)"'. Reason: ''PicklingError("Can\'t pickle <class \'tensorrtserver.api.InferenceServerException\'>: it\'s not the same object as tensorrtserver.api.InferenceServerException",)''.
```

Trying to get my head around this, since the last 2days. 
It should work, coz previously I was using TF-serving in the same architecture and that was working fine.

PS: the same client works fine when executed individually using JUPYTER-LAB

Thanks, any help is appreciated.

**Comment by gr8Adakron** [comment]
@aaronp24 @mkolod @lukeyeager @swarren

**Comment by swarren** [comment]
Please don't mention people that are unrelated to this project; there's nothing we can do to help you. Thanks.

**Comment by gr8Adakron** [comment]
Sorry, I removed it.

**Comment by gr8Adakron** [comment]
@aaronp24

**Comment by rounakskm** [comment]
@gr8Adakron How did you solve this, I am facing a similar problem
