### ISSUE TITLE
taking to too much time for "HTTP client failed: Couldn't connect to server"

### ISSUE THREAD

**Issue by akshay951228** [NVIDIA/tensorrt-inference-server#612]
if the server is not up it was taking to a long time to throw an error that server is not up(HTTP client failed: Couldn't connect to server)

https://github.com/NVIDIA/tensorrt-inference-server/blob/d51f9856b82c642eb6a93f017361fcd5209c6514/src/clients/python/simple_client.py#L63
it would be better if there is the parameter for a timeout in all the tensorrtclient api, otherwise, it was taking a long time

**Comment by GuanLuo** [comment]
How long does it take and are there steps to reproduce your observation?
I tried on my end and the Python client seems to be responsive (server is not running):
```bash
root@f269555eaec5:/opt/tensorrtserver/qa# time clients/simple_client.py 
Health for model simple
Traceback (most recent call last):
  File "clients/simple_client.py", line 66, in <module>
    print("Live: {}".format(health_ctx.is_live()))
  File "/usr/local/lib/python2.7/dist-packages/tensorrtserver/api/__init__.py", line 451, in is_live
    c_void_p(_crequest_health_ctx_live(self._ctx, byref(clive))))
  File "/usr/local/lib/python2.7/dist-packages/tensorrtserver/api/__init__.py", line 239, in _raise_if_error
    raise ex
tensorrtserver.api.InferenceServerException: [ 0] HTTP client failed: Couldn't connect to server

real	0m0.171s
user	0m0.406s
sys	0m0.442s
```

**Comment by CoderHam** [comment]
Closing due to lack of activity. Re-open if needed.

**Comment by Lydia-Lv** [comment]
@GuanLuo  I used C++ client for v20.03，when I stop the triton server docker, it will take 2-20s to get return.
Can I set the connection timeout parameter?

**Comment by GuanLuo** [comment]
@Lydia-Lv Can you try the latest version? And yes you can set the timeout parameter (i.e. [C++](https://github.com/triton-inference-server/server/blob/master/src/clients/c%2B%2B/library/common.h#L199-L207), [Python](https://github.com/triton-inference-server/server/blob/master/src/clients/python/library/tritonclient/http/__init__.py#L150-L155))
