### ISSUE TITLE
Docker Build Failing

### ISSUE THREAD

**Issue by Derongan** [NVIDIA/tensorrt-inference-server#678]
I am building the server using docker as per the instructions on the docs. I am using an EC2 P2 instance. I am running `docker build --pull -t tensorrtserver .` and I am have checked out the v1.5.0 tag/r19.08/505a5696517bdd8313a74509a8c0ecf954df9568

Docker:
```
ii  docker-ce                                                   5:19.03.2~3-0~ubuntu-bionic       amd64        Docker: the open-source application container engine
ii  docker-ce-cli                                               5:19.03.2~3-0~ubuntu-bionic       amd64        Docker CLI: the open-source application container engine
```

Nvidia Packages (incl nvidia container tools)
```
ii  libnvidia-cfg1-418:amd64                                    418.87.00-0ubuntu1                amd64        NVIDIA binary OpenGL/GLX configuration library
ii  libnvidia-common-418                                        418.87.00-0ubuntu1                all          Shared files used by the NVIDIA libraries
ii  libnvidia-compute-418:amd64                                 418.87.00-0ubuntu1                amd64        NVIDIA libcompute package
ii  libnvidia-container-tools                                   1.0.5-1                           amd64        NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64                                  1.0.5-1                           amd64        NVIDIA container runtime library
ii  libnvidia-decode-418:amd64                                  418.87.00-0ubuntu1                amd64        NVIDIA Video Decoding runtime libraries
ii  libnvidia-encode-418:amd64                                  418.87.00-0ubuntu1                amd64        NVENC Video Encoding runtime library
ii  libnvidia-fbc1-418:amd64                                    418.87.00-0ubuntu1                amd64        NVIDIA OpenGL-based Framebuffer Capture runtime library
ii  libnvidia-gl-418:amd64                                      418.87.00-0ubuntu1                amd64        NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
ii  libnvidia-ifr1-418:amd64                                    418.87.00-0ubuntu1                amd64        NVIDIA OpenGL-based Inband Frame Readback runtime library
ii  nvidia-compute-utils-418                                    418.87.00-0ubuntu1                amd64        NVIDIA compute utilities
ii  nvidia-container-toolkit                                    1.0.5-1                           amd64        NVIDIA container runtime hook
ii  nvidia-dkms-418                                             418.87.00-0ubuntu1                amd64        NVIDIA DKMS package
ii  nvidia-driver-418                                           418.87.00-0ubuntu1                amd64        NVIDIA driver metapackage
ii  nvidia-kernel-common-418                                    418.87.00-0ubuntu1                amd64        Shared files used with the kernel module
ii  nvidia-kernel-source-418                                    418.87.00-0ubuntu1                amd64        NVIDIA kernel source package
ii  nvidia-modprobe                                             418.87.00-0ubuntu1                amd64        Load the NVIDIA kernel driver and create device files
ii  nvidia-prime                                                0.8.8.2                           all          Tools to enable NVIDIA's Prime
ii  nvidia-settings                                             418.87.00-0ubuntu1                amd64        Tool for configuring the NVIDIA graphics driver
ii  nvidia-utils-418                                            418.87.00-0ubuntu1                amd64        NVIDIA driver support binaries
ii  xserver-xorg-video-nvidia-418                               418.87.00-0ubuntu1                amd64        NVIDIA binary Xorg driver
```

The build fails with a none to helpful error message:
```
 51%] Building CUDA object CMakeFiles/onnxruntime_providers_cuda.dir/workspace/onnxruntime/onnxruntime/contrib_ops/cuda/tensor/image_scaler_impl.cu.o
/workspace/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena_impl.h(55): warning: integer conversion resulted in a change of sign

/workspace/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena_impl.h(309): warning: integer conversion resulted in a change of sign

/workspace/onnxruntime/cmake/external/protobuf/src/google/protobuf/arena_impl.h(310): warning: integer conversion resulted in a change of sign

[ 51%] Linking CUDA static library libonnxruntime_providers_cuda.a
[ 51%] Built target onnxruntime_providers_cuda
make: *** [all] Error 2
Makefile:140: recipe for target 'all' failed
Traceback (most recent call last):
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 902, in <module>
    sys.exit(main())
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 851, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 424, in build_targets
    run_subprocess(cmd_args)
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 181, in run_subprocess
    return subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '/workspace/build/Release', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
The command '/bin/sh -c python3 /workspace/onnxruntime/tools/ci_build/build.py --build_dir /workspace/build             --config Release $COMMON_BUILD_ARGS             --use_cuda             --cuda_home /usr/local/cuda             --cudnn_home /usr/local/cudnn-$(echo $CUDNN_VERSION | cut -d. -f1-2)/cuda             --update             --build' returned a non-zero code: 1
```

Does anyone have any idea what the issue is, or any troubleshooting I can perform?

Thank you

**Comment by GuanLuo** [comment]
Perhaps it is due to the docker build checked out ONNX Runtime commit without syncing the corresponding submodules, can you try to add the following to Dockerfile and see if it resolves the issue?
https://github.com/NVIDIA/tensorrt-inference-server/blob/master/Dockerfile#L112

**Comment by Derongan** [comment]
That fixed it! Thanks!

**Comment by lazykyama** [comment]
Hi, @GuanLuo. I have one question about this issue. Do you have any plan to backport this fix to previous branches/tags like `r19.08`?
Another guy is also facing the same issue so it's very helpful for many people to backport this to older one.
